/**\file*********************************************************************
 *                                                                     \brief
 *  Basic Win API types
 *
 ****************************************************************************
 */

#ifndef NTL__WIN_WINDEF
#define NTL__WIN_WINDEF

#include "../nt/basedef.hxx"
#include "../nt/teb.hxx"

namespace ntl {

/// Win32 Application support
namespace win {

/**\addtogroup  winapi_types_support *** Win32 API support library **********
 *@{*/


using nt::slist_header;
using nt::single_list_entry;
using nt::slist_entry;
using nt::list_entry;
using nt::list_head;

using nt::access_mask;
using nt::no_access;
using nt::delete_access;
using nt::read_control;
using nt::write_dac;
using nt::write_owner;
using nt::synchronize;
using nt::standard_rights_required;
using nt::standard_rights_read;
using nt::standard_rights_write;
using nt::standard_rights_execute;
using nt::standard_rights_all;
using nt::specific_rights_all;
using nt::access_system_security;
using nt::maximum_allowed;
using nt::generic_read;
using nt::generic_write;
using nt::generic_execute;
using nt::generic_all;

using nt::DllMainReason;


// win32 bool
typedef long bool_t;

struct lasterror
{
  enum type;

  static void set(uint32_t value)
  {
    ntl::nt::teb::instance().LastErrorValue = value;
  }

  static type get()
  {
    return static_cast<type>(ntl::nt::teb::instance().LastErrorValue);
  }

  lasterror()
    :err_(get())
  {}

  lasterror(type error)
    :err_(error)
  {
    set(error);
  }

  lasterror(uint32_t error)
    :err_(static_cast<type>(error))
  {
    set(error);
  }

  lasterror& operator=(const type error)
  {
    err_ = static_cast<type>(error);
    set(error);
  }

  operator type() const { return err_; }
  operator bool() const { return err_ == success; }
  bool operator!() const { return err_ != success; }

  type err_;


  enum type {
    success                                               = 0,
    invalid_function,
    file_not_found,
    path_not_found,
    too_many_open_files,
    access_denied,
    invalid_handle,
    arena_trashed,
    not_enough_memory,
    invalid_block,
    bad_environment,
    bad_format,
    invalid_access,
    invalid_data,
    outofmemory,
    invalid_drive,
    current_directory,
    not_same_device,
    no_more_files,
    write_protect,
    bad_unit,
    not_ready,
    bad_command,
    crc,
    bad_length,
    seek,
    not_dos_disk,
    sector_not_found,
    out_of_paper,
    write_fault,
    read_fault,
    gen_failure,
    sharing_violation,
    lock_violation,
    wrong_disk,
    sharing_buffer_exceeded                               = 36,
    handle_eof                                            = 38,
    handle_disk_full,
    not_supported                                         = 50,
    rem_not_list,
    dup_name,
    bad_netpath,
    network_busy,
    dev_not_exist,
    too_many_cmds,
    adap_hdw_err,
    bad_net_resp,
    unexp_net_err,
    bad_rem_adap,
    printq_full,
    no_spool_space,
    print_cancelled,
    netname_deleted,
    network_access_denied,
    bad_dev_type,
    bad_net_name,
    too_many_names,
    too_many_sess,
    sharing_paused,
    req_not_accep,
    redir_paused,
    file_exists                                           = 80,
    cannot_make                                           = 82,
    fail_i24,
    out_of_structures,
    already_assigned,
    invalid_password,
    invalid_parameter,
    net_write_fault,
    no_proc_slots,
    too_many_semaphores                                   = 100,
    excl_sem_already_owned,
    sem_is_set,
    too_many_sem_requests,
    invalid_at_interrupt_time,
    sem_owner_died,
    sem_user_limit,
    disk_change,
    drive_locked,
    broken_pipe,
    open_failed,
    buffer_overflow,
    disk_full,
    no_more_search_handles,
    invalid_target_handle,
    invalid_category                                      = 117,
    invalid_verify_switch,
    bad_driver_level,
    call_not_implemented,
    sem_timeout,
    insufficient_buffer,
    invalid_name,
    invalid_level,
    no_volume_label,
    mod_not_found,
    proc_not_found,
    wait_no_children,
    child_not_complete,
    direct_access_handle,
    negative_seek,
    seek_on_device,
    is_join_target,
    is_joined,
    is_substed,
    not_joined,
    not_substed,
    join_to_join,
    subst_to_subst,
    join_to_subst,
    subst_to_join,
    busy_drive,
    same_drive,
    dir_not_root,
    dir_not_empty,
    is_subst_path,
    is_join_path,
    path_busy,
    is_subst_target,
    system_trace,
    invalid_event_count,
    too_many_muxwaiters,
    invalid_list_format,
    label_too_long,
    too_many_tcbs,
    signal_refused,
    discarded,
    not_locked,
    bad_threadid_addr,
    bad_arguments,
    bad_pathname,
    signal_pending,
    max_thrds_reached                                     = 164,
    lock_failed                                           = 167,
    busy                                                  = 170,
    cancel_violation                                      = 173,
    atomic_locks_not_supported,
    invalid_segment_number                                = 180,
    invalid_ordinal                                       = 182,
    already_exists,
    invalid_flag_number                                   = 186,
    sem_not_found,
    invalid_starting_codeseg,
    invalid_stackseg,
    invalid_moduletype,
    invalid_exe_signature,
    exe_marked_invalid,
    bad_exe_format,
    iterated_data_exceeds_64k,
    invalid_minallocsize,
    dynlink_from_invalid_ring,
    iopl_not_enabled,
    invalid_segdpl,
    autodataseg_exceeds_64k,
    ring2seg_must_be_movable,
    reloc_chain_xeeds_seglim,
    infloop_in_reloc_chain,
    envvar_not_found,
    no_signal_sent                                        = 205,
    filename_exced_range,
    ring2_stack_in_use,
    meta_expansion_too_long,
    invalid_signal_number,
    thread_1_inactive,
    locked                                                = 212,
    too_many_modules                                      = 214,
    nesting_not_allowed,
    exe_machine_type_mismatch,
    exe_cannot_modify_signed_binary,
    exe_cannot_modify_strong_signed_binary,
    bad_pipe                                              = 230,
    pipe_busy,
    no_data,
    pipe_not_connected,
    more_data,
    vc_disconnected                                       = 240,
    invalid_ea_name                                       = 254,
    ea_list_inconsistent,
    no_more_items                                         = 259,
    cannot_copy                                           = 266,
    directory,
    eas_didnt_fit                                         = 275,
    ea_file_corrupt,
    ea_table_full,
    invalid_ea_handle,
    eas_not_supported                                     = 282,
    not_owner                                             = 288,
    too_many_posts                                        = 298,
    partial_copy,
    oplock_not_granted,
    invalid_oplock_protocol,
    disk_too_fragmented,
    delete_pending,
    mr_mid_not_found                                      = 317,
    scope_not_found,
    invalid_address                                       = 487,
    arithmetic_overflow                                   = 534,
    pipe_connected,
    pipe_listening,
    ea_access_denied                                      = 994,
    operation_aborted,
    io_incomplete,
    io_pending,
    noaccess,
    swaperror,
    stack_overflow                                        = 1001,
    invalid_message,
    can_not_complete,
    invalid_flags,
    unrecognized_volume,
    file_invalid,
    fullscreen_mode,
    no_token,
    baddb,
    badkey,
    cantopen,
    cantread,
    cantwrite,
    registry_recovered,
    registry_corrupt,
    registry_io_failed,
    not_registry_file,
    key_deleted,
    no_log_space,
    key_has_children,
    child_must_be_volatile,
    notify_enum_dir,
    dependent_services_running                            = 1051,
    invalid_service_control,
    service_request_timeout,
    service_no_thread,
    service_database_locked,
    service_already_running,
    invalid_service_account,
    service_disabled,
    circular_dependency,
    service_does_not_exist,
    service_cannot_accept_ctrl,
    service_not_active,
    failed_service_controller_connect,
    exception_in_service,
    database_does_not_exist,
    service_specific_error,
    process_aborted,
    service_dependency_fail,
    service_logon_failed,
    service_start_hang,
    invalid_service_lock,
    service_marked_for_delete,
    service_exists,
    already_running_lkg,
    service_dependency_deleted,
    boot_already_accepted,
    service_never_started,
    duplicate_service_name,
    different_service_account,
    cannot_detect_driver_failure,
    cannot_detect_process_abort,
    no_recovery_program,
    service_not_in_exe,
    not_safeboot_service,
    end_of_media                                          = 1100,
    filemark_detected,
    beginning_of_media,
    setmark_detected,
    no_data_detected,
    partition_failure,
    invalid_block_length,
    device_not_partitioned,
    unable_to_lock_media,
    unable_to_unload_media,
    media_changed,
    bus_reset,
    no_media_in_drive,
    no_unicode_translation,
    dll_init_failed,
    shutdown_in_progress,
    no_shutdown_in_progress,
    io_device,
    serial_no_device,
    irq_busy,
    more_writes,
    counter_timeout,
    floppy_id_mark_not_found,
    floppy_wrong_cylinder,
    floppy_unknown_error,
    floppy_bad_registers,
    disk_recalibrate_failed,
    disk_operation_failed,
    disk_reset_failed,
    eom_overflow,
    not_enough_server_memory,
    possible_deadlock,
    mapped_alignment,
    set_power_state_vetoed                                = 1140,
    set_power_state_failed,
    too_many_links,
    old_win_version                                       = 1150,
    app_wrong_os,
    single_instance_app,
    rmode_app,
    invalid_dll,
    no_association,
    dde_fail,
    dll_not_found,
    no_more_user_handles,
    message_sync_only,
    source_element_empty,
    destination_element_full,
    illegal_element_address,
    magazine_not_present,
    device_reinitialization_needed,
    device_requires_cleaning,
    device_door_open,
    device_not_connected,
    not_found,
    no_match,
    set_not_found,
    point_not_found,
    no_tracking_service,
    no_volume_id,
    unable_to_remove_replaced                             = 1175,
    unable_to_move_replacement,
    unable_to_move_replacement_2,
    journal_delete_in_progress,
    journal_not_active,
    potential_file_found,
    journal_entry_deleted,
    bad_device                                            = 1200,
    connection_unavail,
    device_already_remembered,
    no_net_or_bad_path,
    bad_provider,
    cannot_open_profile,
    bad_profile,
    not_container,
    extended_error,
    invalid_groupname,
    invalid_computername,
    invalid_eventname,
    invalid_domainname,
    invalid_servicename,
    invalid_netname,
    invalid_sharename,
    invalid_passwordname,
    invalid_messagename,
    invalid_messagedest,
    session_credential_conflict,
    remote_session_limit_exceeded,
    dup_domainname,
    no_network,
    cancelled,
    user_mapped_file,
    connection_refused,
    graceful_disconnect,
    address_already_associated,
    address_not_associated,
    connection_invalid,
    connection_active,
    network_unreachable,
    host_unreachable,
    protocol_unreachable,
    port_unreachable,
    request_aborted,
    connection_aborted,
    retry,
    connection_count_limit,
    login_time_restriction,
    login_wksta_restriction,
    incorrect_address,
    already_registered,
    service_not_found,
    not_authenticated,
    not_logged_on,
    continue_,
    already_initialized,
    no_more_devices,
    no_such_site,
    domain_controller_exists,
    only_if_connected,
    override_nochanges,
    bad_user_profile,
    not_supported_on_sbs,
    server_shutdown_in_progress,
    host_down,
    non_account_sid,
    non_domain_sid,
    apphelp_block,
    access_disabled_by_policy,
    reg_nat_consumption,
    cscshare_offline,
    pkinit_failure,
    smartcard_subsystem_failure,
    downgrade_detected,
    machine_locked                                        = 1271,
    callback_supplied_invalid_data                        = 1273,
    sync_foreground_refresh_required,
    driver_blocked,
    invalid_import_of_non_dll,
    access_disabled_webblade,
    access_disabled_webblade_tamper,
    recovery_failure,
    already_fiber,
    already_thread,
    stack_buffer_overrun,
    parameter_quota_exceeded,
    debugger_inactive,
    delay_load_failed,
    vdm_disallowed,
    unidentified_error,
    not_all_assigned                                      = 1300,
    some_not_mapped,
    no_quotas_for_account,
    local_user_session_key,
    null_lm_password,
    unknown_revision,
    revision_mismatch,
    invalid_owner,
    invalid_primary_group,
    no_impersonation_token,
    cant_disable_mandatory,
    no_logon_servers,
    no_such_logon_session,
    no_such_privilege,
    privilege_not_held,
    invalid_account_name,
    user_exists,
    no_such_user,
    group_exists,
    no_such_group,
    member_in_group,
    member_not_in_group,
    last_admin,
    wrong_password,
    ill_formed_password,
    password_restriction,
    logon_failure,
    account_restriction,
    invalid_logon_hours,
    invalid_workstation,
    password_expired,
    account_disabled,
    none_mapped,
    too_many_luids_requested,
    luids_exhausted,
    invalid_sub_authority,
    invalid_acl,
    invalid_sid,
    invalid_security_descr,
    bad_inheritance_acl                                   = 1340,
    server_disabled,
    server_not_disabled,
    invalid_id_authority,
    allotted_space_exceeded,
    invalid_group_attributes,
    bad_impersonation_level,
    cant_open_anonymous,
    bad_validation_class,
    bad_token_type,
    no_security_on_object,
    cant_access_domain_info,
    invalid_server_state,
    invalid_domain_state,
    invalid_domain_role,
    no_such_domain,
    domain_exists,
    domain_limit_exceeded,
    internal_db_corruption,
    internal_error,
    generic_not_mapped,
    bad_descriptor_format,
    not_logon_process,
    logon_session_exists,
    no_such_package,
    bad_logon_session_state,
    logon_session_collision,
    invalid_logon_type,
    cannot_impersonate,
    rxact_invalid_state,
    rxact_commit_failure,
    special_account,
    special_group,
    special_user,
    members_primary_group,
    token_already_in_use,
    no_such_alias,
    member_not_in_alias,
    member_in_alias,
    alias_exists,
    logon_not_granted,
    too_many_secrets,
    secret_too_long,
    internal_db_error,
    too_many_context_ids,
    logon_type_not_granted,
    nt_cross_encryption_required,
    no_such_member,
    invalid_member,
    too_many_sids,
    lm_cross_encryption_required,
    no_inheritance,
    file_corrupt,
    disk_corrupt,
    no_user_session_key,
    license_quota_exceeded,
    wrong_target_name,
    mutual_auth_failed,
    time_skew,
    current_domain_not_allowed,
    invalid_window_handle,
    invalid_menu_handle,
    invalid_cursor_handle,
    invalid_accel_handle,
    invalid_hook_handle,
    invalid_dwp_handle,
    tlw_with_wschild,
    cannot_find_wnd_class,
    window_of_other_thread,
    hotkey_already_registered,
    class_already_exists,
    class_does_not_exist,
    class_has_windows,
    invalid_index,
    invalid_icon_handle,
    private_dialog_index,
    listbox_id_not_found,
    no_wildcard_characters,
    clipboard_not_open,
    hotkey_not_registered,
    window_not_dialog,
    control_id_not_found,
    invalid_combobox_message,
    window_not_combobox,
    invalid_edit_height,
    dc_not_found,
    invalid_hook_filter,
    invalid_filter_proc,
    hook_needs_hmod,
    global_only_hook,
    journal_hook_set,
    hook_not_installed,
    invalid_lb_message,
    setcount_on_bad_lb,
    lb_without_tabstops,
    destroy_object_of_other_thread,
    child_window_menu,
    no_system_menu,
    invalid_msgbox_style,
    invalid_spi_value,
    screen_already_locked,
    hwnds_have_diff_parent,
    not_child_window,
    invalid_gw_command,
    invalid_thread_id,
    non_mdichild_window,
    popup_already_active,
    no_scrollbars,
    invalid_scrollbar_range,
    invalid_showwin_command,
    no_system_resources,
    nonpaged_system_resources,
    paged_system_resources,
    working_set_quota,
    pagefile_quota,
    commitment_limit,
    menu_item_not_found,
    invalid_keyboard_handle,
    hook_type_not_allowed,
    requires_interactive_windowstation,
    timeout,
    invalid_monitor_handle,
    incorrect_size,
    eventlog_file_corrupt                                 = 1500,
    eventlog_cant_start,
    log_file_full,
    eventlog_file_changed,
    install_service_failure                               = 1601,
    install_userexit,
    install_failure,
    install_suspend,
    unknown_product,
    unknown_feature,
    unknown_component,
    unknown_property,
    invalid_handle_state,
    bad_configuration,
    index_absent,
    install_source_absent,
    install_package_version,
    product_uninstalled,
    bad_query_syntax,
    invalid_field,
    device_removed,
    install_already_running,
    install_package_open_failed,
    install_package_invalid,
    install_ui_failure,
    install_log_failure,
    install_language_unsupported,
    install_transform_failure,
    install_package_rejected,
    function_not_called,
    function_failed,
    invalid_table,
    datatype_mismatch,
    unsupported_type,
    create_failed,
    install_temp_unwritable,
    install_platform_unsupported,
    install_notused,
    patch_package_open_failed,
    patch_package_invalid,
    patch_package_unsupported,
    product_version,
    invalid_command_line,
    install_remote_disallowed,
    success_reboot_initiated,
    patch_target_not_found,
    patch_package_rejected,
    install_transform_rejected,
    install_remote_prohibited,
    invalid_user_buffer                                   = 1784,
    unrecognized_media,
    no_trust_lsa_secret,
    no_trust_sam_account,
    trusted_domain_failure,
    trusted_relationship_failure,
    trust_failure,
    netlogon_not_started                                  = 1792,
    account_expired,
    redirector_has_open_handles,
    printer_driver_already_installed,
    unknown_port,
    unknown_printer_driver,
    unknown_printprocessor,
    invalid_separator_file,
    invalid_priority,
    invalid_printer_name,
    printer_already_exists,
    invalid_printer_command,
    invalid_datatype,
    invalid_environment,
    nologon_interdomain_trust_account                     = 1807,
    nologon_workstation_trust_account,
    nologon_server_trust_account,
    domain_trust_inconsistent,
    server_has_open_handles,
    resource_data_not_found,
    resource_type_not_found,
    resource_name_not_found,
    resource_lang_not_found,
    not_enough_quota,
    invalid_time                                          = 1901,
    invalid_form_name,
    invalid_form_size,
    already_waiting,
    printer_deleted,
    invalid_printer_state,
    password_must_change,
    domain_controller_not_found,
    account_locked_out,
    no_sitename                                           = 1919,
    cant_access_file,
    cant_resolve_filename,
    km_driver_blocked                                     = 1930,
    context_expired,
    per_user_trust_quota_exceeded,
    all_user_trust_quota_exceeded,
    user_delete_trust_quota_exceeded,
    authentication_firewall_failed,
    remote_print_connections_blocked,
    invalid_pixel_format                                  = 2000,
    bad_driver,
    invalid_window_style,
    metafile_not_supported,
    transform_not_supported,
    clipping_not_supported,
    invalid_cmm                                           = 2010,
    invalid_profile,
    tag_not_found,
    tag_not_present,
    duplicate_tag,
    profile_not_associated_with_device,
    profile_not_found,
    invalid_colorspace,
    icm_not_enabled,
    deleting_icm_xform,
    invalid_transform,
    colorspace_mismatch,
    invalid_colorindex,
    connected_other_password                              = 2108,
    connected_other_password_default,
    bad_username                                          = 2202,
    not_connected                                         = 2250,
    open_files                                            = 2401,
    active_connections,
    device_in_use                                         = 2404,
    unknown_print_monitor                                 = 3000,
    printer_driver_in_use,
    spool_file_not_found,
    spl_no_startdoc,
    spl_no_addjob,
    print_processor_already_installed,
    print_monitor_already_installed,
    invalid_print_monitor,
    print_monitor_in_use,
    printer_has_jobs_queued,
    success_reboot_required,
    success_restart_required,
    printer_not_found,
    printer_driver_warned,
    printer_driver_blocked,
    wins_internal                                         = 4000,
    can_not_del_local_wins,
    static_init,
    inc_backup,
    full_backup,
    rec_non_existent,
    rpl_not_allowed,
    dhcp_address_conflict                                 = 4100,
    wmi_guid_not_found                                    = 4200,
    wmi_instance_not_found,
    wmi_itemid_not_found,
    wmi_try_again,
    wmi_dp_not_found,
    wmi_unresolved_instance_ref,
    wmi_already_enabled,
    wmi_guid_disconnected,
    wmi_server_unavailable,
    wmi_dp_failed,
    wmi_invalid_mof,
    wmi_invalid_reginfo,
    wmi_already_disabled,
    wmi_read_only,
    wmi_set_failure,
    invalid_media                                         = 4300,
    invalid_library,
    invalid_media_pool,
    drive_media_mismatch,
    media_offline,
    library_offline,
    empty,
    not_empty,
    media_unavailable,
    resource_disabled,
    invalid_cleaner,
    unable_to_clean,
    object_not_found,
    database_failure,
    database_full,
    media_incompatible,
    resource_not_present,
    invalid_operation,
    media_not_available,
    device_not_available,
    request_refused,
    invalid_drive_object,
    library_full,
    medium_not_accessible,
    unable_to_load_medium,
    unable_to_inventory_drive,
    unable_to_inventory_slot,
    unable_to_inventory_transport,
    transport_full,
    controlling_ieport,
    unable_to_eject_mounted_media,
    cleaner_slot_set,
    cleaner_slot_not_set,
    cleaner_cartridge_spent,
    unexpected_omid,
    cant_delete_last_item,
    message_exceeds_max_size,
    volume_contains_sys_files,
    indigenous_type,
    no_supporting_drives,
    cleaner_cartridge_installed,
    ieport_full,
    file_offline                                          = 4350,
    remote_storage_not_active,
    remote_storage_media_error,
    not_a_reparse_point                                   = 4390,
    reparse_attribute_conflict,
    invalid_reparse_data,
    reparse_tag_invalid,
    reparse_tag_mismatch,
    volume_not_sis_enabled                                = 4500,
    dependent_resource_exists                             = 5001,
    dependency_not_found,
    dependency_already_exists,
    resource_not_online,
    host_node_not_available,
    resource_not_available,
    resource_not_found,
    shutdown_cluster,
    cant_evict_active_node,
    object_already_exists,
    object_in_list,
    group_not_available,
    group_not_found,
    group_not_online,
    host_node_not_resource_owner,
    host_node_not_group_owner,
    resmon_create_failed,
    resmon_online_failed,
    resource_online,
    quorum_resource,
    not_quorum_capable,
    cluster_shutting_down,
    invalid_state,
    resource_properties_stored,
    not_quorum_class,
    core_resource,
    quorum_resource_online_failed,
    quorumlog_open_failed,
    clusterlog_corrupt,
    clusterlog_record_exceeds_maxsize,
    clusterlog_exceeds_maxsize,
    clusterlog_chkpoint_not_found,
    clusterlog_not_enough_space,
    quorum_owner_alive,
    network_not_available,
    node_not_available,
    all_nodes_not_available,
    resource_failed,
    cluster_invalid_node,
    cluster_node_exists,
    cluster_join_in_progress,
    cluster_node_not_found,
    cluster_local_node_not_found,
    cluster_network_exists,
    cluster_network_not_found,
    cluster_netinterface_exists,
    cluster_netinterface_not_found,
    cluster_invalid_request,
    cluster_invalid_network_provider,
    cluster_node_down,
    cluster_node_unreachable,
    cluster_node_not_member,
    cluster_join_not_in_progress,
    cluster_invalid_network,
    cluster_node_up                                       = 5056,
    cluster_ipaddr_in_use,
    cluster_node_not_paused,
    cluster_no_security_context,
    cluster_network_not_internal,
    cluster_node_already_up,
    cluster_node_already_down,
    cluster_network_already_online,
    cluster_network_already_offline,
    cluster_node_already_member,
    cluster_last_internal_network,
    cluster_network_has_dependents,
    invalid_operation_on_quorum,
    dependency_not_allowed,
    cluster_node_paused,
    node_cant_host_resource,
    cluster_node_not_ready,
    cluster_node_shutting_down,
    cluster_join_aborted,
    cluster_incompatible_versions,
    cluster_maxnum_of_resources_exceeded,
    cluster_system_config_changed,
    cluster_resource_type_not_found,
    cluster_restype_not_supported,
    cluster_resname_not_found,
    cluster_no_rpc_packages_registered,
    cluster_owner_not_in_preflist,
    cluster_database_seqmismatch,
    resmon_invalid_state,
    cluster_gum_not_locker,
    quorum_disk_not_found,
    database_backup_corrupt,
    cluster_node_already_has_dfs_root,
    resource_property_unchangeable,
    cluster_membership_invalid_state                      = 5890,
    cluster_quorumlog_not_found,
    cluster_membership_halt,
    cluster_instance_id_mismatch,
    cluster_network_not_found_for_ip,
    cluster_property_data_type_mismatch,
    cluster_evict_without_cleanup,
    cluster_parameter_mismatch,
    node_cannot_be_clustered,
    cluster_wrong_os_version,
    cluster_cant_create_dup_cluster_name,
    cluscfg_already_committed,
    cluscfg_rollback_failed,
    cluscfg_system_disk_drive_letter_conflict,
    cluster_old_version,
    cluster_mismatched_computer_acct_name,
    encryption_failed                                     = 6000,
    decryption_failed,
    file_encrypted,
    no_recovery_policy,
    no_efs,
    wrong_efs,
    no_user_keys,
    file_not_encrypted,
    not_export_format,
    file_read_only,
    dir_efs_disallowed,
    efs_server_not_trusted,
    bad_recovery_policy,
    efs_alg_blob_too_big,
    volume_not_support_efs,
    efs_disabled,
    efs_version_not_support,
    no_browser_servers_found                              = 6118,
    ctx_winstation_name_invalid                           = 7001,
    ctx_invalid_pd,
    ctx_pd_not_found,
    ctx_wd_not_found,
    ctx_cannot_make_eventlog_entry,
    ctx_service_name_collision,
    ctx_close_pending,
    ctx_no_outbuf,
    ctx_modem_inf_not_found,
    ctx_invalid_modemname,
    ctx_modem_response_error,
    ctx_modem_response_timeout,
    ctx_modem_response_no_carrier,
    ctx_modem_response_no_dialtone,
    ctx_modem_response_busy,
    ctx_modem_response_voice,
    ctx_td_error,
    ctx_winstation_not_found                              = 7022,
    ctx_winstation_already_exists,
    ctx_winstation_busy,
    ctx_bad_video_mode,
    ctx_graphics_invalid                                  = 7035,
    ctx_logon_disabled                                    = 7037,
    ctx_not_console,
    ctx_client_query_timeout                              = 7040,
    ctx_console_disconnect,
    ctx_console_connect,
    ctx_shadow_denied                                     = 7044,
    ctx_winstation_access_denied,
    ctx_invalid_wd                                        = 7049,
    ctx_shadow_invalid,
    ctx_shadow_disabled,
    ctx_client_license_in_use,
    ctx_client_license_not_set,
    ctx_license_not_available,
    ctx_license_client_invalid,
    ctx_license_expired,
    ctx_shadow_not_running,
    ctx_shadow_ended_by_mode_change,
    activation_count_exceeded,
    ds_not_installed                                      = 8200,
    ds_membership_evaluated_locally,
    ds_no_attribute_or_value,
    ds_invalid_attribute_syntax,
    ds_attribute_type_undefined,
    ds_attribute_or_value_exists,
    ds_busy,
    ds_unavailable,
    ds_no_rids_allocated,
    ds_no_more_rids,
    ds_incorrect_role_owner,
    ds_ridmgr_init_error,
    ds_obj_class_violation,
    ds_cant_on_non_leaf,
    ds_cant_on_rdn,
    ds_cant_mod_obj_class,
    ds_cross_dom_move_error,
    ds_gc_not_available,
    shared_policy,
    policy_object_not_found,
    policy_only_in_ds,
    promotion_active,
    no_promotion_active,
    ds_operations_error                                   = 8224,
    ds_protocol_error,
    ds_timelimit_exceeded,
    ds_sizelimit_exceeded,
    ds_admin_limit_exceeded,
    ds_compare_false,
    ds_compare_true,
    ds_auth_method_not_supported,
    ds_strong_auth_required,
    ds_inappropriate_auth,
    ds_auth_unknown,
    ds_referral,
    ds_unavailable_crit_extension,
    ds_confidentiality_required,
    ds_inappropriate_matching,
    ds_constraint_violation,
    ds_no_such_object,
    ds_alias_problem,
    ds_invalid_dn_syntax,
    ds_is_leaf,
    ds_alias_deref_problem,
    ds_unwilling_to_perform,
    ds_loop_detect,
    ds_naming_violation,
    ds_object_results_too_large,
    ds_affects_multiple_dsas,
    ds_server_down,
    ds_local_error,
    ds_encoding_error,
    ds_decoding_error,
    ds_filter_unknown,
    ds_param_error,
    ds_not_supported,
    ds_no_results_returned,
    ds_control_not_found,
    ds_client_loop,
    ds_referral_limit_exceeded,
    ds_sort_control_missing,
    ds_offset_range_error,
    ds_root_must_be_nc                                    = 8301,
    ds_add_replica_inhibited,
    ds_att_not_def_in_schema,
    ds_max_obj_size_exceeded,
    ds_obj_string_name_exists,
    ds_no_rdn_defined_in_schema,
    ds_rdn_doesnt_match_schema,
    ds_no_requested_atts_found,
    ds_user_buffer_to_small,
    ds_att_is_not_on_obj,
    ds_illegal_mod_operation,
    ds_obj_too_large,
    ds_bad_instance_type,
    ds_masterdsa_required,
    ds_object_class_required,
    ds_missing_required_att,
    ds_att_not_def_for_class,
    ds_att_already_exists,
    ds_cant_add_att_values                                = 8320,
    ds_single_value_constraint,
    ds_range_constraint,
    ds_att_val_already_exists,
    ds_cant_rem_missing_att,
    ds_cant_rem_missing_att_val,
    ds_root_cant_be_subref,
    ds_no_chaining,
    ds_no_chained_eval,
    ds_no_parent_object,
    ds_parent_is_an_alias,
    ds_cant_mix_master_and_reps,
    ds_children_exist,
    ds_obj_not_found,
    ds_aliased_obj_missing,
    ds_bad_name_syntax,
    ds_alias_points_to_alias,
    ds_cant_deref_alias,
    ds_out_of_scope,
    ds_object_being_removed,
    ds_cant_delete_dsa_obj,
    ds_generic_error,
    ds_dsa_must_be_int_master,
    ds_class_not_dsa,
    ds_insuff_access_rights,
    ds_illegal_superior,
    ds_attribute_owned_by_sam,
    ds_name_too_many_parts,
    ds_name_too_long,
    ds_name_value_too_long,
    ds_name_unparseable,
    ds_name_type_unknown,
    ds_not_an_object,
    ds_sec_desc_too_short,
    ds_sec_desc_invalid,
    ds_no_deleted_name,
    ds_subref_must_have_parent,
    ds_ncname_must_be_nc,
    ds_cant_add_system_only,
    ds_class_must_be_concrete,
    ds_invalid_dmd,
    ds_obj_guid_exists,
    ds_not_on_backlink,
    ds_no_crossref_for_nc,
    ds_shutting_down,
    ds_unknown_operation,
    ds_invalid_role_owner,
    ds_couldnt_contact_fsmo,
    ds_cross_nc_dn_rename,
    ds_cant_mod_system_only,
    ds_replicator_only,
    ds_obj_class_not_defined,
    ds_obj_class_not_subclass,
    ds_name_reference_invalid,
    ds_cross_ref_exists,
    ds_cant_del_master_crossref,
    ds_subtree_notify_not_nc_head,
    ds_notify_filter_too_complex,
    ds_dup_rdn,
    ds_dup_oid,
    ds_dup_mapi_id,
    ds_dup_schema_id_guid,
    ds_dup_ldap_display_name,
    ds_semantic_att_test,
    ds_syntax_mismatch,
    ds_exists_in_must_have,
    ds_exists_in_may_have,
    ds_nonexistent_may_have,
    ds_nonexistent_must_have,
    ds_aux_cls_test_fail,
    ds_nonexistent_poss_sup,
    ds_sub_cls_test_fail,
    ds_bad_rdn_att_id_syntax,
    ds_exists_in_aux_cls,
    ds_exists_in_sub_cls,
    ds_exists_in_poss_sup,
    ds_recalcschema_failed,
    ds_tree_delete_not_finished,
    ds_cant_delete,
    ds_att_schema_req_id,
    ds_bad_att_schema_syntax,
    ds_cant_cache_att,
    ds_cant_cache_class,
    ds_cant_remove_att_cache,
    ds_cant_remove_class_cache,
    ds_cant_retrieve_dn,
    ds_missing_supref,
    ds_cant_retrieve_instance,
    ds_code_inconsistency,
    ds_database_error,
    ds_governsid_missing,
    ds_missing_expected_att,
    ds_ncname_missing_cr_ref,
    ds_security_checking_error,
    ds_schema_not_loaded,
    ds_schema_alloc_failed,
    ds_att_schema_req_syntax,
    ds_gcverify_error,
    ds_dra_schema_mismatch,
    ds_cant_find_dsa_obj,
    ds_cant_find_expected_nc,
    ds_cant_find_nc_in_cache,
    ds_cant_retrieve_child,
    ds_security_illegal_modify,
    ds_cant_replace_hidden_rec,
    ds_bad_hierarchy_file,
    ds_build_hierarchy_table_failed,
    ds_config_param_missing,
    ds_counting_ab_indices_failed,
    ds_hierarchy_table_malloc_failed,
    ds_internal_failure,
    ds_unknown_error,
    ds_root_requires_class_top,
    ds_refusing_fsmo_roles,
    ds_missing_fsmo_settings,
    ds_unable_to_surrender_roles,
    ds_dra_generic,
    ds_dra_invalid_parameter,
    ds_dra_busy,
    ds_dra_bad_dn,
    ds_dra_bad_nc,
    ds_dra_dn_exists,
    ds_dra_internal_error,
    ds_dra_inconsistent_dit,
    ds_dra_connection_failed,
    ds_dra_bad_instance_type,
    ds_dra_out_of_mem,
    ds_dra_mail_problem,
    ds_dra_ref_already_exists,
    ds_dra_ref_not_found,
    ds_dra_obj_is_rep_source,
    ds_dra_db_error,
    ds_dra_no_replica,
    ds_dra_access_denied,
    ds_dra_not_supported,
    ds_dra_rpc_cancelled,
    ds_dra_source_disabled,
    ds_dra_sink_disabled,
    ds_dra_name_collision,
    ds_dra_source_reinstalled,
    ds_dra_missing_parent,
    ds_dra_preempted,
    ds_dra_abandon_sync,
    ds_dra_shutdown,
    ds_dra_incompatible_partial_set,
    ds_dra_source_is_partial_replica,
    ds_dra_extn_connection_failed,
    ds_install_schema_mismatch,
    ds_dup_link_id,
    ds_name_error_resolving,
    ds_name_error_not_found,
    ds_name_error_not_unique,
    ds_name_error_no_mapping,
    ds_name_error_domain_only,
    ds_name_error_no_syntactical_mapping,
    ds_constructed_att_mod,
    ds_wrong_om_obj_class,
    ds_dra_repl_pending,
    ds_ds_required,
    ds_invalid_ldap_display_name,
    ds_non_base_search,
    ds_cant_retrieve_atts,
    ds_backlink_without_link,
    ds_epoch_mismatch,
    ds_src_name_mismatch,
    ds_src_and_dst_nc_identical,
    ds_dst_nc_mismatch,
    ds_not_authoritive_for_dst_nc,
    ds_src_guid_mismatch,
    ds_cant_move_deleted_object,
    ds_pdc_operation_in_progress,
    ds_cross_domain_cleanup_reqd,
    ds_illegal_xdom_move_operation,
    ds_cant_with_acct_group_membershps,
    ds_nc_must_have_nc_parent,
    ds_cr_impossible_to_validate,
    ds_dst_domain_not_native,
    ds_missing_infrastructure_container,
    ds_cant_move_account_group,
    ds_cant_move_resource_group,
    ds_invalid_search_flag,
    ds_no_tree_delete_above_nc,
    ds_couldnt_lock_tree_for_delete,
    ds_couldnt_identify_objects_for_tree_delete,
    ds_sam_init_failure,
    ds_sensitive_group_violation,
    ds_cant_mod_primarygroupid,
    ds_illegal_base_schema_mod,
    ds_nonsafe_schema_change,
    ds_schema_update_disallowed,
    ds_cant_create_under_schema,
    ds_install_no_src_sch_version,
    ds_install_no_sch_version_in_inifile,
    ds_invalid_group_type,
    ds_no_nest_globalgroup_in_mixeddomain,
    ds_no_nest_localgroup_in_mixeddomain,
    ds_global_cant_have_local_member,
    ds_global_cant_have_universal_member,
    ds_universal_cant_have_local_member,
    ds_global_cant_have_crossdomain_member,
    ds_local_cant_have_crossdomain_local_member,
    ds_have_primary_members,
    ds_string_sd_conversion_failed,
    ds_naming_master_gc,
    ds_dns_lookup_failure,
    ds_couldnt_update_spns,
    ds_cant_retrieve_sd,
    ds_key_not_unique,
    ds_wrong_linked_att_syntax,
    ds_sam_need_bootkey_password,
    ds_sam_need_bootkey_floppy,
    ds_cant_start,
    ds_init_failure,
    ds_no_pkt_privacy_on_connection,
    ds_source_domain_in_forest,
    ds_destination_domain_not_in_forest,
    ds_destination_auditing_not_enabled,
    ds_cant_find_dc_for_src_domain,
    ds_src_obj_not_group_or_user,
    ds_src_sid_exists_in_forest,
    ds_src_and_dst_object_class_mismatch,
    sam_init_failure,
    ds_dra_schema_info_ship,
    ds_dra_schema_conflict,
    ds_dra_earlier_schema_conflict,
    ds_dra_obj_nc_mismatch,
    ds_nc_still_has_dsas,
    ds_gc_required,
    ds_local_member_of_local_only,
    ds_no_fpo_in_universal_groups,
    ds_cant_add_to_gc,
    ds_no_checkpoint_with_pdc,
    ds_source_auditing_not_enabled,
    ds_cant_create_in_nondomain_nc,
    ds_invalid_name_for_spn,
    ds_filter_uses_contructed_attrs,
    ds_unicodepwd_not_in_quotes,
    ds_machine_account_quota_exceeded,
    ds_must_be_run_on_dst_dc,
    ds_src_dc_must_be_sp4_or_greater,
    ds_cant_tree_delete_critical_obj,
    ds_init_failure_console,
    ds_sam_init_failure_console,
    ds_forest_version_too_high,
    ds_domain_version_too_high,
    ds_forest_version_too_low,
    ds_domain_version_too_low,
    ds_incompatible_version,
    ds_low_dsa_version,
    ds_no_behavior_version_in_mixeddomain,
    ds_not_supported_sort_order,
    ds_name_not_unique,
    ds_machine_account_created_prent4,
    ds_out_of_version_store,
    ds_incompatible_controls_used,
    ds_no_ref_domain,
    ds_reserved_link_id,
    ds_link_id_not_available,
    ds_ag_cant_have_universal_member,
    ds_modifydn_disallowed_by_instance_type,
    ds_no_object_move_in_schema_nc,
    ds_modifydn_disallowed_by_flag,
    ds_modifydn_wrong_grandparent,
    ds_name_error_trust_referral,
    not_supported_on_standard_server,
    ds_cant_access_remote_part_of_ad,
    ds_cr_impossible_to_validate_v2,
    ds_thread_limit_exceeded,
    ds_not_closest,
    ds_cant_derive_spn_without_server_ref,
    ds_single_user_mode_failed,
    ds_ntdscript_syntax_error,
    ds_ntdscript_process_error,
    ds_different_repl_epochs,
    ds_drs_extensions_changed,
    ds_replica_set_change_not_allowed_on_disabled_cr,
    ds_no_msds_intid,
    ds_dup_msds_intid,
    ds_exists_in_rdnattid,
    ds_authorization_failed,
    ds_invalid_script,
    ds_remote_crossref_op_failed,
    ds_cross_ref_busy,
    ds_cant_derive_spn_for_deleted_domain,
    ds_cant_demote_with_writeable_nc,
    ds_duplicate_id_found,
    ds_insufficient_attr_to_create_object,
    ds_group_conversion_error,
    ds_cant_move_app_basic_group,
    ds_cant_move_app_query_group,
    ds_role_not_verified,
    ds_wko_container_cannot_be_special,
    ds_domain_rename_in_progress,
    ds_existing_ad_child_nc,
    ds_repl_lifetime_exceeded,
    ds_disallowed_in_system_container,
    ds_ldap_send_queue_full,
    ds_dra_out_schedule_window,

    wsaeintr                                              = 10004,
    wsaebadf                                              = 10009,
    wsaeacces                                             = 10013,
    wsaefault,
    wsaeinval                                             = 10022,
    wsaemfile                                             = 10024,
    wsaewouldblock                                        = 10035,
    wsaeinprogress,
    wsaealready,
    wsaenotsock,
    wsaedestaddrreq,
    wsaemsgsize,
    wsaeprototype,
    wsaenoprotoopt,
    wsaeprotonosupport,
    wsaesocktnosupport,
    wsaeopnotsupp,
    wsaepfnosupport,
    wsaeafnosupport,
    wsaeaddrinuse,
    wsaeaddrnotavail,
    wsaenetdown,
    wsaenetunreach,
    wsaenetreset,
    wsaeconnaborted,
    wsaeconnreset,
    wsaenobufs,
    wsaeisconn,
    wsaenotconn,
    wsaeshutdown,
    wsaetoomanyrefs,
    wsaetimedout,
    wsaeconnrefused,
    wsaeloop,
    wsaenametoolong,
    wsaehostdown,
    wsaehostunreach,
    wsaenotempty,
    wsaeproclim,
    wsaeusers,
    wsaedquot,
    wsaestale,
    wsaeremote,
    wsaediscon                                            = 10101,
    wsaenomore,
    wsaecancelled,
    wsaeinvalidproctable,
    wsaeinvalidprovider,
    wsaeproviderfailedinit,
    wsaerefused                                           = 10112,

    internet_error_base   = 12000,
    internet_out_of_handles           = internet_error_base + 1,
    internet_timeout                  = internet_error_base + 2,
    internet_extended_error           = internet_error_base + 3,
    internet_internal_error           = internet_error_base + 4,
    internet_invalid_url              = internet_error_base + 5,
    internet_unrecognized_scheme      = internet_error_base + 6,
    internet_name_not_resolved        = internet_error_base + 7,
    internet_protocol_not_found       = internet_error_base + 8,
    internet_invalid_option           = internet_error_base + 9,
    internet_bad_option_length        = internet_error_base + 10,
    internet_option_not_settable      = internet_error_base + 11,
    internet_shutdown                 = internet_error_base + 12,
    internet_incorrect_user_name      = internet_error_base + 13,
    internet_incorrect_password       = internet_error_base + 14,
    internet_login_failure            = internet_error_base + 15,
    internet_invalid_operation        = internet_error_base + 16,
    internet_operation_cancelled      = internet_error_base + 17,
    internet_incorrect_handle_type    = internet_error_base + 18,
    internet_incorrect_handle_state   = internet_error_base + 19,
    internet_not_proxy_request        = internet_error_base + 20,
    internet_registry_value_not_found = internet_error_base + 21,
    internet_bad_registry_parameter   = internet_error_base + 22,
    internet_no_direct_access         = internet_error_base + 23,
    internet_no_context               = internet_error_base + 24,
    internet_no_callback              = internet_error_base + 25,
    internet_request_pending          = internet_error_base + 26,
    internet_incorrect_format         = internet_error_base + 27,
    internet_item_not_found           = internet_error_base + 28,
    internet_cannot_connect           = internet_error_base + 29,
    internet_connection_aborted       = internet_error_base + 30,
    internet_connection_reset         = internet_error_base + 31,
    internet_force_retry              = internet_error_base + 32,
    internet_invalid_proxy_request    = internet_error_base + 33,
    internet_need_ui                  = internet_error_base + 34,

    internet_handle_exists            = internet_error_base + 36,
    internet_sec_cert_date_invalid    = internet_error_base + 37,
    internet_sec_cert_cn_invalid      = internet_error_base + 38,
    internet_http_to_https_on_redir   = internet_error_base + 39,
    internet_https_to_http_on_redir   = internet_error_base + 40,
    internet_mixed_security           = internet_error_base + 41,
    internet_chg_post_is_non_secure   = internet_error_base + 42,
    internet_post_is_non_secure       = internet_error_base + 43,
    internet_client_auth_cert_needed  = internet_error_base + 44,
    internet_invalid_ca               = internet_error_base + 45,
    internet_client_auth_not_setup    = internet_error_base + 46,
    internet_async_thread_failed      = internet_error_base + 47,
    internet_redirect_scheme_change   = internet_error_base + 48,
    internet_dialog_pending           = internet_error_base + 49,
    internet_retry_dialog             = internet_error_base + 50,
    internet_https_http_submit_redir  = internet_error_base + 52,
    internet_insert_cdrom             = internet_error_base + 53,
    internet_fortezza_login_needed    = internet_error_base + 54,
    internet_sec_cert_errors          = internet_error_base + 55,
    internet_sec_cert_no_rev          = internet_error_base + 56,
    internet_sec_cert_rev_failed      = internet_error_base + 57,

    ftp_transfer_in_progress          = internet_error_base + 110,
    ftp_dropped                       = internet_error_base + 111,
    ftp_no_passive_mode               = internet_error_base + 112,

    gopher_protocol_error             = internet_error_base + 130,
    gopher_not_file                   = internet_error_base + 131,
    gopher_data_error                 = internet_error_base + 132,
    gopher_end_of_data                = internet_error_base + 133,
    gopher_invalid_locator            = internet_error_base + 134,
    gopher_incorrect_locator_type     = internet_error_base + 135,
    gopher_not_gopher_plus            = internet_error_base + 136,
    gopher_attribute_not_found        = internet_error_base + 137,
    gopher_unknown_locator            = internet_error_base + 138,

    http_header_not_found             = internet_error_base + 150,
    http_downlevel_server             = internet_error_base + 151,
    http_invalid_server_response      = internet_error_base + 152,
    http_invalid_header               = internet_error_base + 153,
    http_invalid_query_request        = internet_error_base + 154,
    http_header_already_exists        = internet_error_base + 155,
    http_redirect_failed              = internet_error_base + 156,
    http_not_redirected               = internet_error_base + 160,
    http_cookie_needs_confirmation    = internet_error_base + 161,
    http_cookie_declined              = internet_error_base + 162,
    http_redirect_needs_confirmation  = internet_error_base + 168,

    internet_security_channel_error   = internet_error_base + 157,
    internet_unable_to_cache_file     = internet_error_base + 158,
    internet_tcpip_not_installed      = internet_error_base + 159,
    internet_disconnected             = internet_error_base + 163,
    internet_server_unreachable       = internet_error_base + 164,
    internet_proxy_server_unreachable = internet_error_base + 165,

    internet_bad_auto_proxy_script    = internet_error_base + 166,
    internet_unable_to_download_script = internet_error_base + 167,
    internet_sec_invalid_cert         = internet_error_base + 169,
    internet_sec_cert_revoked         = internet_error_base + 170,

    internet_failed_duetosecuritycheck  = internet_error_base + 171,
    internet_not_initialized          = internet_error_base + 172,
    internet_need_msn_sspi_pkg          = internet_error_base + 173,
    internet_login_failure_display_entity_body   = internet_error_base + 174,

    sxs_section_not_found                                 = 14000,
    sxs_cant_gen_actctx,
    sxs_invalid_actctxdata_format,
    sxs_assembly_not_found,
    sxs_manifest_format_error,
    sxs_manifest_parse_error,
    sxs_activation_context_disabled,
    sxs_key_not_found,
    sxs_version_conflict,
    sxs_wrong_section_type,
    sxs_thread_queries_disabled,
    sxs_process_default_already_set,
    sxs_unknown_encoding_group,
    sxs_unknown_encoding,
    sxs_invalid_xml_namespace_uri,
    sxs_root_manifest_dependency_not_installed,
    sxs_leaf_manifest_dependency_not_installed,
    sxs_invalid_assembly_identity_attribute,
    sxs_manifest_missing_required_default_namespace,
    sxs_manifest_invalid_required_default_namespace,
    sxs_private_manifest_cross_path_with_reparse_point,
    sxs_duplicate_dll_name,
    sxs_duplicate_windowclass_name,
    sxs_duplicate_clsid,
    sxs_duplicate_iid,
    sxs_duplicate_tlbid,
    sxs_duplicate_progid,
    sxs_duplicate_assembly_name,
    sxs_file_hash_mismatch,
    sxs_policy_parse_error,
    sxs_xml_e_missingquote,
    sxs_xml_e_commentsyntax,
    sxs_xml_e_badstartnamechar,
    sxs_xml_e_badnamechar,
    sxs_xml_e_badcharinstring,
    sxs_xml_e_xmldeclsyntax,
    sxs_xml_e_badchardata,
    sxs_xml_e_missingwhitespace,
    sxs_xml_e_expectingtagend,
    sxs_xml_e_missingsemicolon,
    sxs_xml_e_unbalancedparen,
    sxs_xml_e_internalerror,
    sxs_xml_e_unexpected_whitespace,
    sxs_xml_e_incomplete_encoding,
    sxs_xml_e_missing_paren,
    sxs_xml_e_expectingclosequote,
    sxs_xml_e_multiple_colons,
    sxs_xml_e_invalid_decimal,
    sxs_xml_e_invalid_hexidecimal,
    sxs_xml_e_invalid_unicode,
    sxs_xml_e_whitespaceorquestionmark,
    sxs_xml_e_unexpectedendtag,
    sxs_xml_e_unclosedtag,
    sxs_xml_e_duplicateattribute,
    sxs_xml_e_multipleroots,
    sxs_xml_e_invalidatrootlevel,
    sxs_xml_e_badxmldecl,
    sxs_xml_e_missingroot,
    sxs_xml_e_unexpectedeof,
    sxs_xml_e_badperefinsubset,
    sxs_xml_e_unclosedstarttag,
    sxs_xml_e_unclosedendtag,
    sxs_xml_e_unclosedstring,
    sxs_xml_e_unclosedcomment,
    sxs_xml_e_uncloseddecl,
    sxs_xml_e_unclosedcdata,
    sxs_xml_e_reservednamespace,
    sxs_xml_e_invalidencoding,
    sxs_xml_e_invalidswitch,
    sxs_xml_e_badxmlcase,
    sxs_xml_e_invalid_standalone,
    sxs_xml_e_unexpected_standalone,
    sxs_xml_e_invalid_version,
    sxs_xml_e_missingequals,
    sxs_protection_recovery_failed,
    sxs_protection_public_key_too_short,
    sxs_protection_catalog_not_valid,
    sxs_untranslatable_hresult,
    sxs_protection_catalog_file_missing,
    sxs_missing_assembly_identity_attribute,
    sxs_invalid_assembly_identity_attribute_name,
    ipsec_qm_policy_exists                                = 13000,
    ipsec_qm_policy_not_found,
    ipsec_qm_policy_in_use,
    ipsec_mm_policy_exists,
    ipsec_mm_policy_not_found,
    ipsec_mm_policy_in_use,
    ipsec_mm_filter_exists,
    ipsec_mm_filter_not_found,
    ipsec_transport_filter_exists,
    ipsec_transport_filter_not_found,
    ipsec_mm_auth_exists,
    ipsec_mm_auth_not_found,
    ipsec_mm_auth_in_use,
    ipsec_default_mm_policy_not_found,
    ipsec_default_mm_auth_not_found,
    ipsec_default_qm_policy_not_found,
    ipsec_tunnel_filter_exists,
    ipsec_tunnel_filter_not_found,
    ipsec_mm_filter_pending_deletion,
    ipsec_transport_filter_pending_deletion,
    ipsec_tunnel_filter_pending_deletion,
    ipsec_mm_policy_pending_deletion,
    ipsec_mm_auth_pending_deletion,
    ipsec_qm_policy_pending_deletion,
    ipsec_ike_neg_status_begin                            = 13800,
    ipsec_ike_auth_fail,
    ipsec_ike_attrib_fail,
    ipsec_ike_negotiation_pending,
    ipsec_ike_general_processing_error,
    ipsec_ike_timed_out,
    ipsec_ike_no_cert,
    ipsec_ike_sa_deleted,
    ipsec_ike_sa_reaped,
    ipsec_ike_mm_acquire_drop,
    ipsec_ike_qm_acquire_drop,
    ipsec_ike_queue_drop_mm,
    ipsec_ike_queue_drop_no_mm,
    ipsec_ike_drop_no_response,
    ipsec_ike_mm_delay_drop,
    ipsec_ike_qm_delay_drop,
    ipsec_ike_error,
    ipsec_ike_crl_failed,
    ipsec_ike_invalid_key_usage,
    ipsec_ike_invalid_cert_type,
    ipsec_ike_no_private_key,
    ipsec_ike_dh_fail                                     = 13822,
    ipsec_ike_invalid_header                              = 13824,
    ipsec_ike_no_policy,
    ipsec_ike_invalid_signature,
    ipsec_ike_kerberos_error,
    ipsec_ike_no_public_key,
    ipsec_ike_process_err,
    ipsec_ike_process_err_sa,
    ipsec_ike_process_err_prop,
    ipsec_ike_process_err_trans,
    ipsec_ike_process_err_ke,
    ipsec_ike_process_err_id,
    ipsec_ike_process_err_cert,
    ipsec_ike_process_err_cert_req,
    ipsec_ike_process_err_hash,
    ipsec_ike_process_err_sig,
    ipsec_ike_process_err_nonce,
    ipsec_ike_process_err_notify,
    ipsec_ike_process_err_delete,
    ipsec_ike_process_err_vendor,
    ipsec_ike_invalid_payload,
    ipsec_ike_load_soft_sa,
    ipsec_ike_soft_sa_torn_down,
    ipsec_ike_invalid_cookie,
    ipsec_ike_no_peer_cert,
    ipsec_ike_peer_crl_failed,
    ipsec_ike_policy_change,
    ipsec_ike_no_mm_policy,
    ipsec_ike_notcbpriv,
    ipsec_ike_secloadfail,
    ipsec_ike_failsspinit,
    ipsec_ike_failqueryssp,
    ipsec_ike_srvacqfail,
    ipsec_ike_srvquerycred,
    ipsec_ike_getspifail,
    ipsec_ike_invalid_filter,
    ipsec_ike_out_of_memory,
    ipsec_ike_add_update_key_failed,
    ipsec_ike_invalid_policy,
    ipsec_ike_unknown_doi,
    ipsec_ike_invalid_situation,
    ipsec_ike_dh_failure,
    ipsec_ike_invalid_group,
    ipsec_ike_encrypt,
    ipsec_ike_decrypt,
    ipsec_ike_policy_match,
    ipsec_ike_unsupported_id,
    ipsec_ike_invalid_hash,
    ipsec_ike_invalid_hash_alg,
    ipsec_ike_invalid_hash_size,
    ipsec_ike_invalid_encrypt_alg,
    ipsec_ike_invalid_auth_alg,
    ipsec_ike_invalid_sig,
    ipsec_ike_load_failed,
    ipsec_ike_rpc_delete,
    ipsec_ike_benign_reinit,
    ipsec_ike_invalid_responder_lifetime_notify,
    ipsec_ike_invalid_cert_keylen                         = 13881,
    ipsec_ike_mm_limit,
    ipsec_ike_negotiation_disabled,
    ipsec_ike_neg_status_end,
  };
};

/**@} winapi_types_support */


}//namespace win
}//namespace ntl

#endif//#ifndef NTL__WIN_WINDEF
